# Generated by Django 4.0.3 on 2022-03-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hour',
            name='busynessLevel',
            field=models.CharField(default='Not Busy', max_length=100),
            preserve_default=False,
        ),
    ]
