# Generated by Django 4.0.3 on 2022-03-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hour',
            old_name='hourofDay',
            new_name='hourOfDay',
        ),
    ]
