# Generated by Django 4.0.3 on 2022-04-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_month_queue_remove_week_weekstartday_hour_isopen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='busynessLevel',
        ),
    ]
